// Products Data - Add, edit, or remove products here
const productsData = [
  {
    id: 1,
    name: "Premium Dog Food - Adult Chicken",
    category: "food",
    subcategory: "dog-food",
    price: 2500,
    originalPrice: 3200,
    image: "images/products/meals.jpg",
    images: [
      "images/products/dog-food-chicken.jpg",
      "images/products/dog-food-chicken-2.jpg",
    ],
    description:
      "High-quality premium dog food made with real chicken. Complete and balanced nutrition for adult dogs of all breeds.",
    features: [
      "Real chicken as first ingredient",
      "No artificial preservatives",
      "Rich in omega fatty acids",
      "Supports healthy skin and coat",
      "Natural antioxidants for immune health",
    ],
    inStock: true,
    rating: 4.8,
    reviews: 124,
    weight: "2.5kg",
    featured: true,
    bestseller: true,
    brand: "PremiumPet",
  },
  {
    id: 2,
    name: "Luxury Cat Bed - Cozy Cave",
    category: "accessories",
    subcategory: "beds",
    price: 3500,
    originalPrice: 4500,
    image: "images/products/cat-bed.jpg",
    images: ["images/products/cat-bed.jpg", "images/products/cat-bed-2.jpg"],
    description:
      "Luxurious, self-warming cat bed that provides comfort and security. Machine washable cover.",
    features: [
      "Self-warming technology",
      "Removable and washable cover",
      "Non-slip bottom",
      "Available in multiple colors",
      "Suitable for cats up to 15lbs",
    ],
    inStock: true,
    rating: 4.9,
    reviews: 89,
    weight: "1.2kg",
    featured: true,
    bestseller: true,
    brand: "CozyPets",
  },
  {
    id: 3,
    name: "Pet Grooming Kit - Professional",
    category: "grooming",
    subcategory: "tools",
    price: 4500,
    originalPrice: 6500,
    image: "images/products/grooming-kit.jpg",
    images: [
      "images/products/grooming-kit.jpg",
      "images/products/grooming-kit-2.jpg",
    ],
    description:
      "Professional 7-piece grooming kit with clippers, scissors, brushes, and nail trimmers.",
    features: [
      "Quiet operation - pet-friendly",
      "7 interchangeable heads",
      "Stainless steel blades",
      "Rechargeable battery",
      "Carrying case included",
    ],
    inStock: true,
    rating: 4.7,
    reviews: 56,
    weight: "1.8kg",
    featured: true,
    bestseller: false,
    brand: "GroomPro",
  },
  {
    id: 4,
    name: "Interactive Dog Toy - Treat Dispenser",
    category: "toys",
    subcategory: "interactive",
    price: 1200,
    originalPrice: 1800,
    image: "images/products/treat-dispenser.jpg",
    images: [
      "images/products/treat-dispenser.jpg",
      "images/products/treat-dispenser-2.jpg",
    ],
    description:
      "Mental stimulation toy that dispenses treats as your dog plays. Adjustable difficulty levels.",
    features: [
      "Adjustable difficulty",
      "Durable non-toxic materials",
      "Dishwasher safe",
      "Promotes mental stimulation",
      "Suitable for all dog sizes",
    ],
    inStock: true,
    rating: 4.6,
    reviews: 203,
    weight: "0.3kg",
    featured: false,
    bestseller: true,
    brand: "PlayPaws",
  },
  {
    id: 5,
    name: "Pet Carrier Backpack - Breathable",
    category: "accessories",
    subcategory: "carriers",
    price: 5500,
    originalPrice: 7500,
    image: "images/products/pet-backpack.jpg",
    images: [
      "images/products/pet-backpack.jpg",
      "images/products/pet-backpack-2.jpg",
    ],
    description:
      "Ventilated, comfortable backpack carrier for small dogs and cats. Perfect for travel and outdoor adventures.",
    features: [
      "Mesh panels for ventilation",
      "Padded shoulder straps",
      "Safety leash inside",
      "Multiple pockets for storage",
      "Airline approved",
    ],
    inStock: true,
    rating: 4.8,
    reviews: 67,
    weight: "1.1kg",
    featured: true,
    bestseller: false,
    brand: "TravelPet",
  },
  {
    id: 6,
    name: "Natural Cat Litter - Clumping",
    category: "supplies",
    subcategory: "litter",
    price: 800,
    originalPrice: 1200,
    image: "images/products/cat-litter.jpg",
    images: ["images/products/cat-litter.jpg"],
    description:
      "Eco-friendly, dust-free clumping cat litter made from natural materials. 99% dust-free formula.",
    features: [
      "99% dust-free",
      "Superior odor control",
      "Natural clumping",
      "Biodegradable",
      "Long-lasting",
    ],
    inStock: true,
    rating: 4.5,
    reviews: 178,
    weight: "5kg",
    featured: false,
    bestseller: false,
    brand: "EcoPet",
  },
  {
    id: 7,
    name: "Pet Harness - Reflective",
    category: "accessories",
    subcategory: "collars-harnesses",
    price: 1800,
    originalPrice: 2500,
    image: "images/products/harness.jpg",
    images: ["images/products/harness.jpg", "images/products/harness-2.jpg"],
    description:
      "Comfortable, no-pull harness with reflective strips for safety during night walks.",
    features: [
      "Reflective stitching",
      "Padded chest plate",
      "Quick-release buckles",
      "Adjustable straps",
      "Available in 5 sizes",
    ],
    inStock: true,
    rating: 4.7,
    reviews: 145,
    weight: "0.25kg",
    featured: false,
    bestseller: true,
    brand: "SafeWalk",
  },
  {
    id: 8,
    name: "Pet Dental Care Kit",
    category: "health",
    subcategory: "dental",
    price: 950,
    originalPrice: 1500,
    image: "images/products/dental-kit.jpg",
    images: ["images/products/dental-kit.jpg"],
    description:
      "Complete dental care kit with toothbrush, toothpaste, and finger brush for pets.",
    features: [
      "Enzymatic toothpaste",
      "Soft bristle brush",
      "Finger brush included",
      "Chicken flavor pets love",
      "Vet recommended",
    ],
    inStock: true,
    rating: 4.4,
    reviews: 92,
    weight: "0.15kg",
    featured: false,
    bestseller: false,
    brand: "DentaPet",
  },
  {
    id: 9,
    name: "Puppy Training Pads (50 pack)",
    category: "supplies",
    subcategory: "training",
    price: 1500,
    originalPrice: 2200,
    image: "images/products/training-pads.jpg",
    images: ["images/products/training-pads.jpg"],
    description:
      "Super absorbent puppy training pads with quick-dry surface and leak-proof backing.",
    features: [
      "6-layer protection",
      "Quick-dry surface",
      "Leak-proof backing",
      "Attracts puppies naturally",
      "Odor control technology",
    ],
    inStock: true,
    rating: 4.6,
    reviews: 234,
    weight: "0.8kg",
    featured: false,
    bestseller: true,
    brand: "TrainEasy",
  },
  {
    id: 10,
    name: "Pet Water Fountain",
    category: "accessories",
    subcategory: "feeders",
    price: 4200,
    originalPrice: 5500,
    image: "images/products/water-fountain.jpg",
    images: [
      "images/products/water-fountain.jpg",
      "images/products/water-fountain-2.jpg",
    ],
    description:
      "Stainless steel water fountain with triple filtration system to encourage pets to drink more water.",
    features: [
      "Triple filtration system",
      "Large 2.5L capacity",
      "Ultra-quiet pump",
      "LED light for night",
      "Dishwasher safe parts",
    ],
    inStock: false,
    rating: 4.9,
    reviews: 45,
    weight: "1.4kg",
    featured: false,
    bestseller: false,
    brand: "PureFlow",
  },
];

// Product Categories
const productCategories = [
  { id: "all", label: "All Products", icon: "bx-grid-alt" },
  { id: "food", label: "Pet Food", icon: "bx-bowl-hot" },
  { id: "accessories", label: "Accessories", icon: "bx-collar" },
  { id: "grooming", label: "Grooming", icon: "bx-cut" },
  { id: "toys", label: "Toys", icon: "bx-toy" },
  { id: "health", label: "Health & Wellness", icon: "bx-heart" },
  { id: "supplies", label: "Supplies", icon: "bx-package" },
];

// WhatsApp number for inquiries
const WHATSAPP_NUMBER = "254798503335";

// Function to format price in KES
function formatPrice(price) {
  return `KES ${price.toLocaleString()}`;
}

// Function to calculate discount percentage
function getDiscountPercentage(original, current) {
  if (!original) return 0;
  return Math.round(((original - current) / original) * 100);
}
